bird_dict = {
    0.0: 'ABBOTTS BABBLER',
    1.0: 'ABBOTTS BOOBY',
    2.0: 'ABYSSINIAN GROUND HORNBILL',
    3.0: 'AFRICAN CROWNED CRANE',
    4.0: 'AFRICAN EMERALD CUCKOO',
    5.0: 'AFRICAN FIREFINCH',
    6.0: 'AFRICAN OYSTER CATCHER',
    7.0: 'AFRICAN PIED HORNBILL',
    8.0: 'AFRICAN PYGMY GOOSE',
    9.0: 'ALBATROSS',
    10.0: 'ALBERTS TOWHEE',
    11.0: 'ALEXANDRINE PARAKEET',
    12.0: 'ALPINE CHOUGH',
    13.0: 'ALTAMIRA YELLOWTHROAT',
    14.0: 'AMERICAN AVOCET',
    15.0: 'AMERICAN BITTERN',
    16.0: 'AMERICAN COOT',
    17.0: 'AMERICAN FLAMINGO',
    18.0: 'AMERICAN GOLDFINCH',
    19.0: 'AMERICAN KESTREL'
}

